CREATE TABLE Departamento (
  Dnumero INTEGER UNSIGNED NOT NULL,
  NSSGER INTEGER UNSIGNED NOT NULL,
  DNome VARCHAR(20) NOT NULL,
  DataInicioGer DATE NULL,
  PRIMARY KEY(Dnumero),
  INDEX Departamento_FKIndex1(NSSGER)
);

CREATE TABLE Dependente (
  NSSEMP INTEGER UNSIGNED NOT NULL,
  NomeDependente VARCHAR(255) NOT NULL,
  DTNasc DATE NULL,
  Parentesco VARCHAR(45) NULL,
  INDEX Dependente_FKIndex1(NSSEMP)
);

CREATE TABLE Empregado (
  NSS INTEGER UNSIGNED NOT NULL,
  DNUM INTEGER UNSIGNED NOT NULL,
  NSSSUPER INTEGER UNSIGNED NOT NULL,
  Pnome VARCHAR(20) NOT NULL,
  Salario DECIMAL NULL,
  PRIMARY KEY(NSS),
  INDEX Empregado_FKIndex1(DNUM),
  INDEX Empregado_FKIndex2(NSSSUPER)
);

CREATE TABLE Projeto (
  PNumero INTEGER UNSIGNED NOT NULL,
  DNO INTEGER UNSIGNED NOT NULL,
  PNome VARCHAR(45) NOT NULL,
  PLocalizacao VARCHAR(45) NULL,
  PRIMARY KEY(PNumero),
  INDEX Projeto_FKIndex1(DNO)
);

CREATE TABLE Trabalha_em (
  NSSE INTEGER UNSIGNED NOT NULL,
  PNO INTEGER UNSIGNED NOT NULL,
  Horas INTEGER UNSIGNED NULL,
  PRIMARY KEY(NSSE, PNO),
  INDEX Empregado_has_Projeto_FKIndex1(NSSE),
  INDEX Empregado_has_Projeto_FKIndex2(PNO)
);


